name: Spell Check MPM Docs

on:
  pull_request:
    branches:
      - master
    paths:
      - 'docs-gb/**'

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ› Checkout Code
        uses: actions/checkout@v3

      - name: ğŸ§‘â€ğŸ« Run Vale Spell Check
        uses: simbo/vale-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: 'docs-gb/'
